# Generated by Django 6.0.5 on 2026-05-14 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('opportunity_type', models.CharField(choices=[('Internship', 'Internship'), ('Scholarship', 'Scholarship'), ('Competition', 'Competition'), ('COOP', 'COOP'), ('Bootcamp', 'Bootcamp'), ('Volunteering', 'Volunteering'), ('Program', 'Program')], default='Internship', max_length=32)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('external_url', models.URLField()),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(null=True, blank=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['opportunity__application_deadline'],
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'unique_together': {('user', 'opportunity')},
            },
        ),
    ]
