# Generated by Django 6.0.5 on 2026-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='is_paid',
            field=models.BooleanField(blank=True, help_text='True=paid, False=unpaid, None=not applicable (e.g. competitions)', null=True),
        ),
    ]
